apiVersion: batch/v1
kind: Job
metadata:
  name: ds-graph-job
spec:
  template:
    metadata:
      name: ds-graph-job
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: {{ .Values.dataServices.securityContext.runAsUser }}
        runAsGroup: {{ .Values.dataServices.securityContext.runAsGroup }}
        fsGroup: {{ .Values.dataServices.securityContext.runAsGroup }}
      containers:
        - name: ds-graph-analyzer
          image: {{ .Values.dataServices.image.repository }}:{{ .Values.dataServices.image.tag }}
          imagePullPolicy: {{ .Values.dataServices.image.pullPolicy }}
          command: ["bash"]
          stdin: True
          tty: True
          volumeMounts:
            - name: ds-sources-volume
              mountPath: /Data_services_storage
              {{- if .Values.dataServices.sourcesVolume.nfs_mount_subpath }}
              subPath: {{ .Values.dataServices.sourcesVolume.nfs_mount_subpath }}
              {{- end }}
            - name: ds-sources-volume
              mountPath: /Data_services_logs
              subPath: {{ .Values.dataServices.sourcesVolume.nfs_mount_subpath }}logs
            - name: ds-graphs-volume
              mountPath: /Data_services_graphs
              {{- if .Values.dataServices.graphsVolume.nfs_mount_subpath }}
              subPath: {{ .Values.dataServices.graphsVolume.nfs_mount_subpath }}
              {{- end }}
            {{- if .Values.dataServices.extraVolume.use_extra_volume }}
            - name: ds-extra-volume
              mountPath: /Data_services_extra
              {{- if .Values.dataServices.extraVolume.nfs_mount_subpath }}
              subPath: {{ .Values.dataServices.extraVolume.nfs_mount_subpath }}
              {{- end }}
            {{- end }}
            - mountPath: /data
              name: ds-neo4j-scratch-volume
          env:
            - name: DATA_SERVICES_STORAGE
              value: /Data_services_storage
            - name: DATA_SERVICES_GRAPHS
              value: /Data_services_graphs
            {{- if .Values.dataServices.useLocalGraphSpec }}
            - name: DATA_SERVICES_GRAPH_SPEC
              value: {{ .Values.dataServices.graphSpec }}
            {{- else }}
            - name: DATA_SERVICES_GRAPH_SPEC_URL
              value: {{ .Values.dataServices.graphSpec}}
            {{- end }}
            - name: DATA_SERVICES_LOGS
              value: /Data_services_logs
            - name: DATA_SERVICES_NEO4J_PASSWORD
              value: ds-password
            - name: DATA_SERVICES_OUTPUT_URL
              value: {{ .Values.dataServices.outputURL }}
            {{- if .Values.dataServices.httpsProxy.useProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.dataServices.httpsProxy.proxyURL }}
            {{- end }}
            {{- if .Values.dataServices.normalization.nodeNormEndpoint }}
            - name: NODE_NORMALIZATION_ENDPOINT
              value: {{ .Values.dataServices.normalization.nodeNormEndpoint }}
            {{- end }}
            {{- if .Values.dataServices.normalization.edgeNormEndpoint }}
            - name: EDGE_NORMALIZATION_ENDPOINT
              value: {{ .Values.dataServices.normalization.edgeNormEndpoint }}
            {{- end }}
            - name: DRUGCENTRAL_DB_HOST
              value: {{ .Values.drugcentral.host | quote }}
            - name: DRUGCENTRAL_DB_USER
              value: {{ .Values.drugcentral.user | quote }}
            - name: DRUGCENTRAL_DB_PASSWORD
              value: {{ .Values.drugcentral.password | quote}}
            - name: DRUGCENTRAL_DB_PORT
              value: {{ .Values.drugcentral.port | quote }}
            - name: DRUGCENTRAL_DB_NAME
              value: {{ .Values.drugcentral.db_name | quote }}
            - name: PHAROS_DB_HOST
              value: {{ .Values.pharos.host | quote }}
            - name: PHAROS_DB_USER
              value: {{ .Values.pharos.user | quote }}
            - name: PHAROS_DB_PASSWORD
              value: {{ .Values.pharos.password | quote }}
            - name: PHAROS_DB_PORT
              value: {{ .Values.pharos.port | quote }}
            - name: PHAROS_DB_NAME
              value: {{ .Values.pharos.db_name | quote }}
          resources:
            {{- toYaml .Values.dataServices.resources | nindent 12 }}
      {{- if .Values.dataServices.buildMode }}
      initContainers:
        - name: ds-graph-builder
          image: {{ .Values.dataServices.image.repository }}:{{ .Values.dataServices.image.tag }}
          imagePullPolicy: {{ .Values.dataServices.image.pullPolicy }}
          args: ["python", "/Data_services/Common/build_manager.py", {{ .Values.dataServices.graphID }} ]
          volumeMounts:
            - mountPath: /Data_services_storage
              name: ds-sources-volume
              {{- if .Values.dataServices.sourcesVolume.nfs_mount_subpath }}
              subPath: {{ .Values.dataServices.sourcesVolume.nfs_mount_subpath }}
              {{- end }}
            - mountPath: /Data_services_logs
              name: ds-sources-volume
              subPath: {{ .Values.dataServices.sourcesVolume.nfs_mount_subpath }}logs
            - mountPath: /Data_services_graphs
              name: ds-graphs-volume
              {{- if .Values.dataServices.graphsVolume.nfs_mount_subpath }}
              subPath: {{ .Values.dataServices.graphsVolume.nfs_mount_subpath }}
              {{- end }}
            - mountPath: /data
              name: ds-neo4j-scratch-volume
          env:
            - name: DATA_SERVICES_STORAGE
              value: /Data_services_storage
            - name: DATA_SERVICES_GRAPHS
              value: /Data_services_graphs
            {{- if .Values.dataServices.useLocalGraphSpec }}
            - name: DATA_SERVICES_GRAPH_SPEC
              value: {{ .Values.dataServices.graphSpec }}
            {{- else }}
            - name: DATA_SERVICES_GRAPH_SPEC_URL
              value: {{ .Values.dataServices.graphSpec }}
            {{- end }}
            - name: DATA_SERVICES_LOGS
              value: /Data_services_logs
            - name: DATA_SERVICES_NEO4J_PASSWORD
              value: ds-password
            - name: DATA_SERVICES_OUTPUT_URL
              value: {{ .Values.dataServices.outputURL }}
            {{- if .Values.dataServices.httpsProxy.useProxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.dataServices.httpsProxy.proxyURL }}
            {{- end }}
            {{- if .Values.dataServices.normalization.nodeNormEndpoint }}
            - name: NODE_NORMALIZATION_ENDPOINT
              value: {{ .Values.dataServices.normalization.nodeNormEndpoint }}
            {{- end }}
            {{- if .Values.dataServices.normalization.edgeNormEndpoint }}
            - name: EDGE_NORMALIZATION_ENDPOINT
              value: {{ .Values.dataServices.normalization.edgeNormEndpoint }}
            {{- end }}
            - name: DRUGCENTRAL_DB_HOST
              value: {{ .Values.drugcentral.host | quote }}
            - name: DRUGCENTRAL_DB_USER
              value: {{ .Values.drugcentral.user | quote }}
            - name: DRUGCENTRAL_DB_PASSWORD
              value: {{ .Values.drugcentral.password | quote }}
            - name: DRUGCENTRAL_DB_PORT
              value: {{ .Values.drugcentral.port | quote }}
            - name: DRUGCENTRAL_DB_NAME
              value: {{ .Values.drugcentral.db_name | quote }}
            - name: PHAROS_DB_HOST
              value: {{ .Values.pharos.host | quote }}
            - name: PHAROS_DB_USER
              value: {{ .Values.pharos.user | quote }}
            - name: PHAROS_DB_PASSWORD
              value: {{ .Values.pharos.password | quote }}
            - name: PHAROS_DB_PORT
              value: {{ .Values.pharos.port | quote }}
            - name: PHAROS_DB_NAME
              value: {{ .Values.pharos.db_name | quote }}
          resources:
            {{- toYaml .Values.dataServices.resources | nindent 12 }}
      {{- end }}
      volumes:
        {{- if .Values.dataServices.sourcesVolume.use_nfs }}
        - name: ds-sources-volume
          nfs:
            server: {{ .Values.dataServices.sourcesVolume.nfs_server }}
            path: {{ .Values.dataServices.sourcesVolume.nfs_path }}
        {{- else }}
        - name: ds-sources-volume
          persistentVolumeClaim:
            claimName: ds-sources-pvc
        {{- end }}
        {{- if .Values.dataServices.graphsVolume.use_nfs }}
        - name: ds-graphs-volume
          nfs:
            server: {{ .Values.dataServices.graphsVolume.nfs_server }}
            path: {{ .Values.dataServices.graphsVolume.nfs_path }}
        {{- else }}
        - name: ds-graphs-volume
          persistentVolumeClaim:
            claimName: ds-graphs-pvc
        {{- end }}
        {{- if .Values.dataServices.extraVolume.use_extra_volume }}
        - name: ds-extra-volume
          nfs:
            server: {{ .Values.dataServices.extraVolume.nfs_server }}
            path: {{ .Values.dataServices.extraVolume.nfs_path }}
        {{- end }}
        - name: ds-neo4j-scratch-volume
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName:
                resources:
                  requests:
                    storage: {{ .Values.dataServices.neo4jScratchVolume.size }}
  backoffLimit: 0
